### PR TITLE
2.8x update

### PR DESCRIPTION
**Pull request by p2or**
Hi @Radivarig, 

updated the addon for 2.8x including _icons_, _proper panel registration_ and I also changed `tex` to `face_map` attribute. To me, all seems to work as expected. What do you think?

Cheers,
Christian

### CODE REVIEW

**Comment by Radivarig** [comment]
Hi @p2or thank you for the effort. There already is a 2.8x branch since beta started https://github.com/Radivarig/UvSquares/tree/upgrade7-80_2.
I will merge that one to master soon now that 2.80 is released.

**Comment by p2or** [comment]
Hi @Radivarig,

thanks, noticed. However, consider that my patch fixes 2 issues of your 2.8x branch (bmesh `face_map` attribute as well as the `panel seperator` issue).

Cheers,
Christian

**Comment by Radivarig** [comment]
@p2or Interesting, I'll definitely include those commits. Thanks!

**Comment by Radivarig** [comment]
@p2or do you maybe know what is the purpose of this line anyway. Is it still needed?
```py
bm.faces.layers.face_map.verify()
```
On the current 2.80 branch I just commented it out.

**Comment by p2or** [comment]
Hi @Radivarig,

I think this call was (and probably is) required to associate/store the transformed UV's to the `bmesh` data in the first place. Also [`face_map.verify()`](https://docs.blender.org/api/current/bmesh.types.html?highlight=face_map#bmesh.types.BMLayerAccessFace.face_map) returns a _verified bmesh layer_, which might be nice for cleanup purposes. However, I did not test it extensively, just tried to replace the deprecated [`tex`](https://docs.blender.org/api/blender_python_api_current/bmesh.types.html?highlight=tex#bmesh.types.BMLayerAccessFace.tex) layer. 

Cheers,
Christian

**Pull request closed without merging**
