### PR TITLE
Add multi island support

### PR DESCRIPTION
**Pull request by JoseConseco**
Add multi island support

### CODE REVIEW

**Comment by WeCode4Fun** [comment]
I tested it. I get this error:

```
location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 913, in execute
    uv_island_lists = self.__get_island(bm)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 897, in __get_island
    self.__parse_island(bm, face_idx, faces_left, current_island)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 884, in __parse_island
    island.append({'face': bm.faces[face_idx]})
IndexError: BMElemSeq[index]: index 6 out of range

```

and this one

```
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 889, in __parse_island
    self.__parse_island(bm, cf, faces_left, island)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 889, in __parse_island
    self.__parse_island(bm, cf, faces_left, island)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 889, in __parse_island
    self.__parse_island(bm, cf, faces_left, island)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 889, in __parse_island
    self.__parse_island(bm, cf, faces_left, island)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 889, in __parse_island
    self.__parse_island(bm, cf, faces_left, island)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 889, in __parse_island
    self.__parse_island(bm, cf, faces_left, island)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 889, in __parse_island
    self.__parse_island(bm, cf, faces_left, island)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 889, in __parse_island
    self.__parse_island(bm, cf, faces_left, island)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 889, in __parse_island
    self.__parse_island(bm, cf, faces_left, island)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UvSquares-multi-island\uv_squares.py", line 884, in __parse_island
    island.append({'face': bm.faces[face_idx]})

IndexError: BMElemSeq[index]: index 80 out of range
```

No idea how to reproduce it though, unfortunately. It just happens all of a sudden. When I save the blend file and reload it, it works again.

**Comment by JoseConseco** [comment]
Fixed. Thanks for report

**Comment by WeCode4Fun** [comment]
Thanks! I tested it, no more errors.

**Comment by Radivarig** [comment]
Commits contained in #11 . Continuing there.

**Pull request closed without merging**
